on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: OS-check

jobs:
  OS-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-16.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
          - {os: ubuntu-16.04,   r: 'oldrel',  rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_TOKEN: ${{ secrets.GHTOKEN2 }}
      GITHUB_PAT: ${{ secrets.GHTOKEN2 }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps("scRNASeq/",dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      # - name: Install XQuartz on macOS
      #   if: runner.os == 'macOS'
      #   run: brew cask install xquartz

      - name: Install System Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y glpk-utils
          sudo apt-get install -y libcurl4-openssl-dev
        shell: bash {0}
        
      - name: Install XML
        if: runner.os == 'Windows'
        run: |
          install.packages("XML", type = "source")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps("scRNASeq/",dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("BiocManager")
          BiocManager::install("rmarkdown")
          BiocManager::install("devtools")
          BiocManager::install("RockefellerUniversity/compileCourses",subdir="compileCourses")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Install package
        if: github.ref == 'refs/heads/master' 
        run: |
          devtools::install("scRNASeq/",dependencies = TRUE,quick = TRUE)
        shell: Rscript {0}

      - name: CompileCourse
        run: |
          require(compileCourses)
          compileCourses::compileSingleCourseMaterial(repo="RockefellerUniversity",subdir="scRNASeq",branch="master")
        shell: Rscript {0}
